### ISSUE TITLE
README needs a project introduction

### ISSUE THREAD

**Issue by lornajane** [aiven/python-notebooks-for-apache-kafka#1]
If a developer found this repo via search, not via the blog post, what would they need to know? Let's do an overview "this is a demo, you can try these notebooks, Aiven has a free trial or link to kafka docs for running locally" ... that sort of thing. I think also a note about opening an issue with any suggested additions or questions might be nice.

**Comment by ftisiot** [comment]
Added Intro, comment about running Kafka locally or on Aiven and suggestion for opening issues

**Comment by lornajane** [comment]
(just add a note about why the pull request was closed when you close it - looks like the change came in via another route or something?)
